
package gob.cpccs.utilidades.webService.Bsg.senescyt;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@SuppressWarnings("serial")
@WebFault(name = "ConsWsFault", targetNamespace = "http://10.180.1.154:8080/ConsultaTitulosSenescytWSv3/ServicioConsultaTitulo")
public class ConsWsException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Object faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ConsWsException(String message, Object faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ConsWsException(String message, Object faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: java.lang.Object
     */
    public Object getFaultInfo() {
        return faultInfo;
    }

}
