
package gob.cpccs.utilidades.webService.Bsg.senescyt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioConsultaTituloService", targetNamespace = "http://10.180.1.154:8080/ConsultaTitulosSenescytWSv3/ServicioConsultaTitulo", wsdlLocation = "https://www.bsg.gob.ec/sw/SENESCYT/BSGSW04_Consultar_Titulos?wsdl")
public class ServicioConsultaTituloService
    extends Service
{

    private final static URL SERVICIOCONSULTATITULOSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOCONSULTATITULOSERVICE_EXCEPTION;
    private final static QName SERVICIOCONSULTATITULOSERVICE_QNAME = new QName("http://10.180.1.154:8080/ConsultaTitulosSenescytWSv3/ServicioConsultaTitulo", "ServicioConsultaTituloService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.bsg.gob.ec/sw/SENESCYT/BSGSW04_Consultar_Titulos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOCONSULTATITULOSERVICE_WSDL_LOCATION = url;
        SERVICIOCONSULTATITULOSERVICE_EXCEPTION = e;
    }

    public ServicioConsultaTituloService() {
        super(__getWsdlLocation(), SERVICIOCONSULTATITULOSERVICE_QNAME);
    }

    public ServicioConsultaTituloService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOCONSULTATITULOSERVICE_QNAME, features);
    }

    public ServicioConsultaTituloService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOCONSULTATITULOSERVICE_QNAME);
    }

    public ServicioConsultaTituloService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOCONSULTATITULOSERVICE_QNAME, features);
    }

    public ServicioConsultaTituloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioConsultaTituloService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSConsultaTitulosService
     */
    @WebEndpoint(name = "WSConsultaTitulosServicePort")
    public WSConsultaTitulosService getWSConsultaTitulosServicePort() {
        return super.getPort(new QName("http://10.180.1.154:8080/ConsultaTitulosSenescytWSv3/ServicioConsultaTitulo", "WSConsultaTitulosServicePort"), WSConsultaTitulosService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSConsultaTitulosService
     */
    @WebEndpoint(name = "WSConsultaTitulosServicePort")
    public WSConsultaTitulosService getWSConsultaTitulosServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://10.180.1.154:8080/ConsultaTitulosSenescytWSv3/ServicioConsultaTitulo", "WSConsultaTitulosServicePort"), WSConsultaTitulosService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOCONSULTATITULOSERVICE_EXCEPTION!= null) {
            throw SERVICIOCONSULTATITULOSERVICE_EXCEPTION;
        }
        return SERVICIOCONSULTATITULOSERVICE_WSDL_LOCATION;
    }

}
