
package gob.cpccs.utilidades.webService.Bsg.registroCivil;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaCiudadano", targetNamespace = "http://www.registrocivil.gob.ec", wsdlLocation = "https://www.bsg.gob.ec/sw/RC/BSGSW03_Consultar_Ciudadano?wsdl")
public class ConsultaCiudadano_Service
    extends Service
{

    private final static URL CONSULTACIUDADANO_WSDL_LOCATION;
    private final static WebServiceException CONSULTACIUDADANO_EXCEPTION;
    private final static QName CONSULTACIUDADANO_QNAME = new QName("http://www.registrocivil.gob.ec", "ConsultaCiudadano");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.bsg.gob.ec/sw/RC/BSGSW03_Consultar_Ciudadano?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTACIUDADANO_WSDL_LOCATION = url;
        CONSULTACIUDADANO_EXCEPTION = e;
    }

    public ConsultaCiudadano_Service() {
        super(__getWsdlLocation(), CONSULTACIUDADANO_QNAME);
    }

    public ConsultaCiudadano_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTACIUDADANO_QNAME, features);
    }

    public ConsultaCiudadano_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTACIUDADANO_QNAME);
    }

    public ConsultaCiudadano_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTACIUDADANO_QNAME, features);
    }

    public ConsultaCiudadano_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaCiudadano_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaCiudadano
     */
    @WebEndpoint(name = "ConsultaCiudadanoPort")
    public ConsultaCiudadano getConsultaCiudadanoPort() {
        return super.getPort(new QName("http://www.registrocivil.gob.ec", "ConsultaCiudadanoPort"), ConsultaCiudadano.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaCiudadano
     */
    @WebEndpoint(name = "ConsultaCiudadanoPort")
    public ConsultaCiudadano getConsultaCiudadanoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.registrocivil.gob.ec", "ConsultaCiudadanoPort"), ConsultaCiudadano.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTACIUDADANO_EXCEPTION!= null) {
            throw CONSULTACIUDADANO_EXCEPTION;
        }
        return CONSULTACIUDADANO_WSDL_LOCATION;
    }

}
