
package gob.cpccs.utilidades.webService.Bsg.sri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceContribuyenteService", targetNamespace = "http://sri.gov.ec/wsConsultaContribuyente", wsdlLocation = "https://www.bsg.gob.ec/sw/SRI/BSGSW01_Consultar_RucSRI?wsdl")
public class WebServiceContribuyenteService
    extends Service
{

    private final static URL WEBSERVICECONTRIBUYENTESERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICECONTRIBUYENTESERVICE_EXCEPTION;
    private final static QName WEBSERVICECONTRIBUYENTESERVICE_QNAME = new QName("http://sri.gov.ec/wsConsultaContribuyente", "WebServiceContribuyenteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.bsg.gob.ec/sw/SRI/BSGSW01_Consultar_RucSRI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICECONTRIBUYENTESERVICE_WSDL_LOCATION = url;
        WEBSERVICECONTRIBUYENTESERVICE_EXCEPTION = e;
    }

    public WebServiceContribuyenteService() {
        super(__getWsdlLocation(), WEBSERVICECONTRIBUYENTESERVICE_QNAME);
    }

    public WebServiceContribuyenteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICECONTRIBUYENTESERVICE_QNAME, features);
    }

    public WebServiceContribuyenteService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICECONTRIBUYENTESERVICE_QNAME);
    }

    public WebServiceContribuyenteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICECONTRIBUYENTESERVICE_QNAME, features);
    }

    public WebServiceContribuyenteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceContribuyenteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsConsultaContribuyente
     */
    @WebEndpoint(name = "wsConsultaContribuyentePort")
    public WsConsultaContribuyente getWsConsultaContribuyentePort() {
        return super.getPort(new QName("http://sri.gov.ec/wsConsultaContribuyente", "wsConsultaContribuyentePort"), WsConsultaContribuyente.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsConsultaContribuyente
     */
    @WebEndpoint(name = "wsConsultaContribuyentePort")
    public WsConsultaContribuyente getWsConsultaContribuyentePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sri.gov.ec/wsConsultaContribuyente", "wsConsultaContribuyentePort"), WsConsultaContribuyente.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICECONTRIBUYENTESERVICE_EXCEPTION!= null) {
            throw WEBSERVICECONTRIBUYENTESERVICE_EXCEPTION;
        }
        return WEBSERVICECONTRIBUYENTESERVICE_WSDL_LOCATION;
    }

}
