
package gob.cpccs.utilidades.webService.Bsg.registroCivil;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultaCiudadano", targetNamespace = "http://www.registrocivil.gob.ec")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaCiudadano {


    /**
     * 
     * @param nui
     * @param codigoInstitucion
     * @param individualDactilar
     * @param usuario
     * @param contrasenia
     * @param codigoAgencia
     * @return
     *     returns gob.cpccs.utilidades.webService.Bsg.registroCivil.Ciudadano
     */
    @WebMethod(operationName = "BusquedaPorNuiIndividual", action = "http://www.registrocivil.gob.ec/BusquedaPorNuiIndividual")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BusquedaPorNuiIndividual", targetNamespace = "http://www.registrocivil.gob.ec", className = "gob.cpccs.utilidades.webService.Bsg.registroCivil.BusquedaPorNuiIndividual")
    @ResponseWrapper(localName = "BusquedaPorNuiIndividualResponse", targetNamespace = "http://www.registrocivil.gob.ec", className = "gob.cpccs.utilidades.webService.Bsg.registroCivil.BusquedaPorNuiIndividualResponse")
    public Ciudadano busquedaPorNuiIndividual(
        @WebParam(name = "CodigoInstitucion", targetNamespace = "")
        String codigoInstitucion,
        @WebParam(name = "CodigoAgencia", targetNamespace = "")
        String codigoAgencia,
        @WebParam(name = "Usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "Contrasenia", targetNamespace = "")
        String contrasenia,
        @WebParam(name = "NUI", targetNamespace = "")
        String nui,
        @WebParam(name = "IndividualDactilar", targetNamespace = "")
        String individualDactilar);

    /**
     * 
     * @param nui
     * @param codigoInstitucion
     * @param usuario
     * @param contrasenia
     * @param codigoAgencia
     * @return
     *     returns gob.cpccs.utilidades.webService.Bsg.registroCivil.Ciudadano
     */
    @WebMethod(operationName = "BusquedaPorNui", action = "http://www.registrocivil.gob.ec/BusquedaPorNui")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BusquedaPorNui", targetNamespace = "http://www.registrocivil.gob.ec", className = "gob.cpccs.utilidades.webService.Bsg.registroCivil.BusquedaPorNui")
    @ResponseWrapper(localName = "BusquedaPorNuiResponse", targetNamespace = "http://www.registrocivil.gob.ec", className = "gob.cpccs.utilidades.webService.Bsg.registroCivil.BusquedaPorNuiResponse")
    public Ciudadano busquedaPorNui(
        @WebParam(name = "CodigoInstitucion", targetNamespace = "")
        String codigoInstitucion,
        @WebParam(name = "CodigoAgencia", targetNamespace = "")
        String codigoAgencia,
        @WebParam(name = "Usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "Contrasenia", targetNamespace = "")
        String contrasenia,
        @WebParam(name = "NUI", targetNamespace = "")
        String nui);

    /**
     * 
     * @param edadInicio
     * @param apellido2
     * @param apellido1
     * @param edadFinal
     * @param codigoInstitucion
     * @param usuario
     * @param contrasenia
     * @param nombre2
     * @param sexo
     * @param nombre1
     * @param codigoAgencia
     * @return
     *     returns gob.cpccs.utilidades.webService.Bsg.registroCivil.Ciudadanos
     */
    @WebMethod(operationName = "BusquedaPorNombre", action = "http://www.registrocivil.gob.ec/BusquedaPorNombre")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BusquedaPorNombre", targetNamespace = "http://www.registrocivil.gob.ec", className = "gob.cpccs.utilidades.webService.Bsg.registroCivil.BusquedaPorNombre")
    @ResponseWrapper(localName = "BusquedaPorNombreResponse", targetNamespace = "http://www.registrocivil.gob.ec", className = "gob.cpccs.utilidades.webService.Bsg.registroCivil.BusquedaPorNombreResponse")
    public Ciudadanos busquedaPorNombre(
        @WebParam(name = "CodigoInstitucion", targetNamespace = "")
        String codigoInstitucion,
        @WebParam(name = "CodigoAgencia", targetNamespace = "")
        String codigoAgencia,
        @WebParam(name = "Usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "Contrasenia", targetNamespace = "")
        String contrasenia,
        @WebParam(name = "Apellido1", targetNamespace = "")
        String apellido1,
        @WebParam(name = "Apellido2", targetNamespace = "")
        String apellido2,
        @WebParam(name = "Nombre1", targetNamespace = "")
        String nombre1,
        @WebParam(name = "Nombre2", targetNamespace = "")
        String nombre2,
        @WebParam(name = "EdadInicio", targetNamespace = "")
        String edadInicio,
        @WebParam(name = "EdadFinal", targetNamespace = "")
        String edadFinal,
        @WebParam(name = "Sexo", targetNamespace = "")
        String sexo);

}
