
package gob.cpccs.utilidades.webService.Bsg.sri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsConsultaContribuyente", targetNamespace = "http://sri.gov.ec/wsConsultaContribuyente")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsConsultaContribuyente {


    /**
     * 
     * @param numeroRuc
     * @return
     *     returns gob.cpccs.utilidades.webService.Bsg.sri.ContribuyenteCompleto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerCompletoContactos", targetNamespace = "http://sri.gov.ec/wsConsultaContribuyente", className = "gob.cpccs.utilidades.webService.Bsg.sri.ObtenerCompletoContactos")
    @ResponseWrapper(localName = "obtenerCompletoContactosResponse", targetNamespace = "http://sri.gov.ec/wsConsultaContribuyente", className = "gob.cpccs.utilidades.webService.Bsg.sri.ObtenerCompletoContactosResponse")
    public ContribuyenteCompleto obtenerCompletoContactos(
        @WebParam(name = "numeroRuc", targetNamespace = "")
        String numeroRuc);

    /**
     * 
     * @param numeroRuc
     * @param fuenteDatos
     * @return
     *     returns gob.cpccs.utilidades.webService.Bsg.sri.Contribuyente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerSimple", targetNamespace = "http://sri.gov.ec/wsConsultaContribuyente", className = "gob.cpccs.utilidades.webService.Bsg.sri.ObtenerSimple")
    @ResponseWrapper(localName = "obtenerSimpleResponse", targetNamespace = "http://sri.gov.ec/wsConsultaContribuyente", className = "gob.cpccs.utilidades.webService.Bsg.sri.ObtenerSimpleResponse")
    public Contribuyente obtenerSimple(
        @WebParam(name = "numeroRuc", targetNamespace = "")
        String numeroRuc,
        @WebParam(name = "fuenteDatos", targetNamespace = "")
        String fuenteDatos);

    /**
     * 
     * @param numeroRuc
     * @return
     *     returns gob.cpccs.utilidades.webService.Bsg.sri.ContribuyenteOnLine
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatos", targetNamespace = "http://sri.gov.ec/wsConsultaContribuyente", className = "gob.cpccs.utilidades.webService.Bsg.sri.ObtenerDatos")
    @ResponseWrapper(localName = "obtenerDatosResponse", targetNamespace = "http://sri.gov.ec/wsConsultaContribuyente", className = "gob.cpccs.utilidades.webService.Bsg.sri.ObtenerDatosResponse")
    public ContribuyenteOnLine obtenerDatos(
        @WebParam(name = "numeroRuc", targetNamespace = "")
        String numeroRuc);

    /**
     * 
     * @param numeroRuc
     * @param fuenteDatos
     * @return
     *     returns gob.cpccs.utilidades.webService.Bsg.sri.ContribuyenteCompleto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerCompleto", targetNamespace = "http://sri.gov.ec/wsConsultaContribuyente", className = "gob.cpccs.utilidades.webService.Bsg.sri.ObtenerCompleto")
    @ResponseWrapper(localName = "obtenerCompletoResponse", targetNamespace = "http://sri.gov.ec/wsConsultaContribuyente", className = "gob.cpccs.utilidades.webService.Bsg.sri.ObtenerCompletoResponse")
    public ContribuyenteCompleto obtenerCompleto(
        @WebParam(name = "numeroRuc", targetNamespace = "")
        String numeroRuc,
        @WebParam(name = "fuenteDatos", targetNamespace = "")
        String fuenteDatos);

}
